/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.taller.tallermecanico.view;
import com.taller.tallermecanico.dao.OdtDao;
import com.taller.tallermecanico.model.Odt;
import com.taller.tallermecanico.view.EditarOdtView;

/**
 *
 * @author rafaelvales
 */


public class EditarOdtView extends javax.swing.JFrame {
    
    private java.util.Map<String, Integer> clienteMap = new java.util.HashMap<>();
    private java.util.Map<String, Integer> mecanicoMap = new java.util.HashMap<>();

    /**
     * Creates new form EditarOdtView
     */
    private Odt odt;

public EditarOdtView(Odt odt) {
    this.odt = odt;
    initComponents();
    cargarCombos(); 
    setLocationRelativeTo(null);
    setTitle("Editar ODT");

    
    jTextField1.setText(odt.getDescripcion());
    jTextField2.setText(String.valueOf(odt.getCostoTotal()));
}
    public EditarOdtView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cliente:");

        jLabel2.setText("Mecanico:");

        jLabel3.setText("Problema:");

        jLabel4.setText("Precio:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String descripcion = jTextField1.getText().trim();
    String precioStr = jTextField2.getText().trim();

    if (descripcion.isEmpty() || precioStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Completa todos los campos.");
        return;
    }

    double precio;
    try {
        precio = Double.parseDouble(precioStr);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El precio debe ser numérico.");
        return;
    }

   
    String clienteSeleccionado = (String) jComboBox1.getSelectedItem();
    String mecanicoSeleccionado = (String) jComboBox2.getSelectedItem();

    if (clienteSeleccionado == null || mecanicoSeleccionado == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar cliente y mecánico.");
        return;
    }

    
    Integer clienteId = clienteMap.get(clienteSeleccionado);
    Integer mecanicoId = mecanicoMap.get(mecanicoSeleccionado);

    if (clienteId == null || mecanicoId == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al obtener IDs de cliente o mecánico.");
        return;
    }

   
    odt.setDescripcion(descripcion);
    odt.setCostoTotal(precio);
    odt.getCliente().setId(clienteId);
    odt.getMecanico().setId(mecanicoId);

    
    com.taller.tallermecanico.dao.OdtDao dao = new com.taller.tallermecanico.dao.OdtDao();
    boolean ok = dao.actualizarOdt(odt); // ⚠️ Asegurate de tener este método en OdtDao

    if (ok) {
        javax.swing.JOptionPane.showMessageDialog(this, "ODT actualizada con éxito.");
        new ListaOdtView().setVisible(true);
        dispose();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar ODT.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
private static class ClienteComboItem {
    private final int id;
    private final String nombre;

    public ClienteComboItem(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return nombre; // lo que se muestra en el combo
    }
}

private static class MecanicoComboItem {
    private final int id;
    private final String nombre;

    public MecanicoComboItem(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return nombre;
    }
}

private void cargarCombos() {
    
    com.taller.tallermecanico.dao.ClienteDao clienteDao = new com.taller.tallermecanico.dao.ClienteDao();
    var clientes = clienteDao.listarClientes();
    jComboBox1.removeAllItems();
    clienteMap.clear();

    for (var c : clientes) {
        String label = c.getNombre() + " (ID: " + c.getId() + ")";
        clienteMap.put(label, c.getId());
        jComboBox1.addItem(label);

     
        if (c.getId() == odt.getCliente().getId()) {
            jComboBox1.setSelectedItem(label);
        }
    }

    
    com.taller.tallermecanico.dao.MecanicoDao mecanicoDao = new com.taller.tallermecanico.dao.MecanicoDao();
    var mecanicos = mecanicoDao.listarMecanicos();
    jComboBox2.removeAllItems();
    mecanicoMap.clear();

    for (var m : mecanicos) {
        String label = m.getNombre() + " (ID: " + m.getId() + ")";
        mecanicoMap.put(label, m.getId());
        jComboBox2.addItem(label);

        if (m.getId() == odt.getMecanico().getId()) {
            jComboBox2.setSelectedItem(label);
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
