/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.taller.tallermecanico.view;
import com.taller.tallermecanico.dao.OdtDao;
import com.taller.tallermecanico.model.Odt;
import com.taller.tallermecanico.view.EditarOdtView;

/**
 * Ventana de edición de orden de trabajo (ODT) para modificar órdenes de trabajo existentes.
 * Esta ventana proporciona una interfaz de formulario para editar información de la orden de trabajo
 * incluyendo cliente, mecánico, descripción del problema y costo.
 * 
 * @author rafaelvales
 */
public class EditarOdtView extends javax.swing.JFrame {
    
    /** Mapa que almacena nombres de clientes y sus IDs correspondientes para la selección del cuadro combinado. */
    private java.util.Map<String, Integer> clienteMap = new java.util.HashMap<>();
    
    /** Mapa que almacena nombres de mecánicos y sus IDs correspondientes para la selección del cuadro combinado. */
    private java.util.Map<String, Integer> mecanicoMap = new java.util.HashMap<>();

    /** El objeto orden de trabajo que se está editando. */
    private Odt odt;

/**
 * Crea una nueva instancia de EditarOdtView con la orden de trabajo especificada.
 * Inicializa los componentes de la interfaz gráfica, carga datos de clientes y mecánicos en los cuadros combinados,
 * y pobla el formulario con la información actual de la orden de trabajo.
 *
 * @param odt el objeto orden de trabajo a editar
 */
public EditarOdtView(Odt odt) {
    this.odt = odt;
    initComponents();
    cargarCombos(); 
    setLocationRelativeTo(null);
    setTitle("Editar ODT");

    
    jTextField1.setText(odt.getDescripcion());
    jTextField2.setText(String.valueOf(odt.getCostoTotal()));
}

    /**
     * Constructor por defecto que crea una instancia vacía de EditarOdtView.
     * Este constructor se proporciona para compatibilidad pero no debe usarse directamente.
     */
    public EditarOdtView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cliente:");

        jLabel2.setText("Mecanico:");

        jLabel3.setText("Problema:");

        jLabel4.setText("Precio:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(242, 242, 242))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento de acción para el campo de texto de descripción del problema.
     * Actualmente no se realiza ninguna acción.
     *
     * @param evt el evento de acción que activó este método
     */
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * Maneja el evento de acción para el campo de texto del precio.
     * Actualmente no se realiza ninguna acción.
     *
     * @param evt el evento de acción que activó este método
     */
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * Maneja el evento de acción para el botón de guardar.
     * Valida los campos de entrada, actualiza el objeto orden de trabajo y guarda los cambios en la base de datos.
     * Abre la vista de lista de órdenes de trabajo y cierra la ventana actual en caso de actualización exitosa.
     *
     * @param evt el evento de acción que activó este método
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String descripcion = jTextField1.getText().trim();
    String precioStr = jTextField2.getText().trim();

    if (descripcion.isEmpty() || precioStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Completa todos los campos.");
        return;
    }

    double precio;
    try {
        precio = Double.parseDouble(precioStr);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El precio debe ser numérico.");
        return;
    }

   
    String clienteSeleccionado = (String) jComboBox1.getSelectedItem();
    String mecanicoSeleccionado = (String) jComboBox2.getSelectedItem();

    if (clienteSeleccionado == null || mecanicoSeleccionado == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar cliente y mecánico.");
        return;
    }

    
    Integer clienteId = clienteMap.get(clienteSeleccionado);
    Integer mecanicoId = mecanicoMap.get(mecanicoSeleccionado);

    if (clienteId == null || mecanicoId == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al obtener IDs de cliente o mecánico.");
        return;
    }

   
    odt.setDescripcion(descripcion);
    odt.setCostoTotal(precio);
    odt.getCliente().setId(clienteId);
    odt.getMecanico().setId(mecanicoId);

    
    com.taller.tallermecanico.dao.OdtDao dao = new com.taller.tallermecanico.dao.OdtDao();
    boolean ok = dao.actualizarOdt(odt); // ⚠️ Asegurate de tener este método en OdtDao

    if (ok) {
        javax.swing.JOptionPane.showMessageDialog(this, "ODT actualizada con éxito.");
        new ListaOdtView().setVisible(true);
        dispose();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar ODT.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
/**
 * Clase interna que representa un elemento de cliente en el cuadro combinado.
 * Almacena tanto el ID como el nombre del cliente para fines de visualización y selección.
 */
private static class ClienteComboItem {
    /** El identificador único del cliente. */
    private final int id;
    
    /** El nombre del cliente. */
    private final String nombre;

    /**
     * Construye un ClienteComboItem con el ID y nombre especificados.
     *
     * @param id el identificador único del cliente
     * @param nombre el nombre del cliente
     */
    public ClienteComboItem(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    /**
     * Obtiene el identificador único del cliente.
     *
     * @return el ID del cliente
     */
    public int getId() {
        return id;
    }

    /**
     * Devuelve el nombre del cliente como representación en cadena.
     *
     * @return el nombre del cliente
     */
    @Override
    public String toString() {
        return nombre; // lo que se muestra en el combo
    }
}

/**
 * Clase interna que representa un elemento de mecánico en el cuadro combinado.
 * Almacena tanto el ID como el nombre del mecánico para fines de visualización y selección.
 */
private static class MecanicoComboItem {
    /** El identificador único del mecánico. */
    private final int id;
    
    /** El nombre del mecánico. */
    private final String nombre;

    /**
     * Construye un MecanicoComboItem con el ID y nombre especificados.
     *
     * @param id el identificador único del mecánico
     * @param nombre el nombre del mecánico
     */
    public MecanicoComboItem(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    /**
     * Obtiene el identificador único del mecánico.
     *
     * @return el ID del mecánico
     */
    public int getId() {
        return id;
    }

    /**
     * Devuelve el nombre del mecánico como representación en cadena.
     *
     * @return el nombre del mecánico
     */
    @Override
    public String toString() {
        return nombre;
    }
}

/**
 * Carga los datos de clientes y mecánicos en sus respectivos cuadros combinados.
 * Recupera todos los clientes y mecánicos de la base de datos, popula los cuadros combinados,
 * y preselecciona el cliente y mecánico actuales asociados con la orden de trabajo.
 */
private void cargarCombos() {
    
    com.taller.tallermecanico.dao.ClienteDao clienteDao = new com.taller.tallermecanico.dao.ClienteDao();
    var clientes = clienteDao.listarClientes();
    jComboBox1.removeAllItems();
    clienteMap.clear();

    for (var c : clientes) {
        String label = c.getNombre() + " (ID: " + c.getId() + ")";
        clienteMap.put(label, c.getId());
        jComboBox1.addItem(label);

     
        if (c.getId() == odt.getCliente().getId()) {
            jComboBox1.setSelectedItem(label);
        }
    }

    
    com.taller.tallermecanico.dao.MecanicoDao mecanicoDao = new com.taller.tallermecanico.dao.MecanicoDao();
    var mecanicos = mecanicoDao.listarMecanicos();
    jComboBox2.removeAllItems();
    mecanicoMap.clear();

    for (var m : mecanicos) {
        String label = m.getNombre() + " (ID: " + m.getId() + ")";
        mecanicoMap.put(label, m.getId());
        jComboBox2.addItem(label);

        if (m.getId() == odt.getMecanico().getId()) {
            jComboBox2.setSelectedItem(label);
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
