package com.taller.tallermecanico.view;

import com.taller.tallermecanico.dao.ClienteDao;
import com.taller.tallermecanico.model.Cliente;
import com.taller.tallermecanico.model.Mecanico;
import com.taller.tallermecanico.dao.MecanicoDao;
import com.taller.tallermecanico.model.Odt;
import javax.swing.JOptionPane;
import java.time.LocalDate;



/**
 * Ventana de gestión de órdenes de trabajo (ODT) para crear y gestionar órdenes de trabajo.
 * Esta ventana proporciona una interfaz de formulario para crear órdenes de trabajo, incluyendo
 * selección de cliente y mecánico, descripción del problema e información de costo.
 * 
 * @author rafaelvales
 */
public class OdtView extends javax.swing.JFrame {

    /**
     * Crea una nueva instancia de OdtView e inicializa los componentes de la interfaz gráfica.
     * Carga los datos de clientes y mecánicos en los cuadros combinados y configura la validación de entrada
     * para el campo de costo para aceptar entrada numérica con soporte para punto decimal.
     */
    public OdtView() {
        initComponents();
        cargarCombos();
           jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
    public void keyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.' && c != ',') {
            evt.consume(); 
        }
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor ODT");

        jLabel1.setText("Cliente:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Mecanico:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Problema:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio:");

        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Listar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento de acción para el campo de texto de descripción del problema.
     * Actualmente no se realiza ninguna acción.
     *
     * @param evt el evento de acción que activó este método
     */
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * Maneja el evento de acción para el botón de menú.
     * Regresa a la vista del menú principal y cierra la ventana actual.
     *
     * @param evt el evento de acción que activó este método
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainView main = new MainView();
        main.setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Maneja el evento de acción para el botón de guardar.
     * Valida los campos de entrada, crea un nuevo objeto orden de trabajo y lo guarda en la base de datos.
     * Establece el estado predeterminado como "Pendiente" y calcula la fecha de entrega estimada.
     * Muestra mensajes de éxito o error según corresponda y limpia el formulario en caso de éxito.
     *
     * @param evt el evento de acción que activó este método
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
        ClienteComboItem clienteItem = (ClienteComboItem) jComboBox1.getSelectedItem();
        MecanicoComboItem mecanicoItem = (MecanicoComboItem) jComboBox2.getSelectedItem();

        if (clienteItem == null || mecanicoItem == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente y un mecánico.");
            return;
        }

        String descripcion = jTextField1.getText().trim();
        if (descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La descripción del problema no puede estar vacía.");
            return;
        }

        double costo;
        try {
            costo = Double.parseDouble(jTextField2.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El costo debe ser un número válido.");
            return;
        }

        Odt odt = new Odt();
        odt.setCliente(new Cliente(clienteItem.getId(), clienteItem.toString(), "", ""));
        odt.setMecanico(new Mecanico(mecanicoItem.getId(), mecanicoItem.toString(), 0, "", 0));
        odt.setDescripcion(descripcion);
        odt.setCostoTotal(costo);
        odt.setEstado("Pendiente");
        odt.setFechaIngreso(LocalDate.now());
        odt.setFechaEntrega(LocalDate.now().plusDays(7)); // entrega estimada

        boolean guardado = new com.taller.tallermecanico.dao.OdtDao().guardarOdt(odt);

        if (guardado) {
            JOptionPane.showMessageDialog(this, "ODT guardada correctamente.");
            jTextField1.setText("");
            jTextField2.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar la ODT.");
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Maneja el evento de acción para el botón de listar.
     * Abre la vista de lista de órdenes de trabajo y cierra la ventana actual.
     *
     * @param evt el evento de acción que activó este método
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new ListaOdtView().setVisible(true);   
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * Maneja el evento de acción para el botón de cancelar.
     * Solicita confirmación al usuario antes de salir de la aplicación.
     *
     * @param evt el evento de acción que activó este método
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
        this,
        "¿Estás seguro de que querés salir de la aplicación?",
        "Salir",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0); 
    } 
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * Maneja el evento de acción para el cuadro combinado de cliente.
     * Actualmente no se realiza ninguna acción.
     *
     * @param evt el evento de acción que activó este método
     */
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * Método principal para lanzar la ventana OdtView.
     * Configura el aspecto Nimbus y muestra la ventana de gestión de órdenes de trabajo.
     *
     * @param args los argumentos de línea de comandos (no se utilizan)
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OdtView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OdtView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OdtView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OdtView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OdtView().setVisible(true);
            }
        });
    }

/**
 * Clase interna que representa un elemento de cliente en el cuadro combinado.
 * Almacena tanto el ID como el nombre del cliente para fines de visualización y selección.
 */
private static class ClienteComboItem {
    /** El identificador único del cliente. */
    private final int id;
    
    /** El nombre del cliente. */
    private final String nombre;

    /**
     * Construye un ClienteComboItem con el ID y nombre especificados.
     *
     * @param id el identificador único del cliente
     * @param nombre el nombre del cliente
     */
    public ClienteComboItem(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    /**
     * Obtiene el identificador único del cliente.
     *
     * @return el ID del cliente
     */
    public int getId() {
        return id;
    }

    /**
     * Devuelve el nombre del cliente como representación en cadena.
     *
     * @return el nombre del cliente
     */
    @Override
    public String toString() {
        return nombre;
    }
}

/**
 * Clase interna que representa un elemento de mecánico en el cuadro combinado.
 * Almacena tanto el ID como el nombre del mecánico para fines de visualización y selección.
 */
private static class MecanicoComboItem {
    /** El identificador único del mecánico. */
    private final int id;
    
    /** El nombre del mecánico. */
    private final String nombre;

    /**
     * Construye un MecanicoComboItem con el ID y nombre especificados.
     *
     * @param id el identificador único del mecánico
     * @param nombre el nombre del mecánico
     */
    public MecanicoComboItem(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    /**
     * Obtiene el identificador único del mecánico.
     *
     * @return el ID del mecánico
     */
    public int getId() {
        return id;
    }

    /**
     * Devuelve el nombre del mecánico como representación en cadena.
     *
     * @return el nombre del mecánico
     */
    @Override
    public String toString() {
        return nombre;
    }
}

/**
 * Carga los datos de clientes y mecánicos en sus respectivos cuadros combinados.
 * Recupera todos los clientes y mecánicos de la base de datos y popula
 * los cuadros combinados con objetos ClienteComboItem y MecanicoComboItem.
 */
private void cargarCombos() {
    ClienteDao clienteDao = new ClienteDao();
    java.util.List<Cliente> clientes = clienteDao.listarClientes();

    
    jComboBox1.removeAllItems();
    for (Cliente c : clientes) {
        ((javax.swing.JComboBox) jComboBox1).addItem(new ClienteComboItem(c.getId(), c.getNombre()));
    }

    MecanicoDao mecanicoDao = new MecanicoDao();
    java.util.List<com.taller.tallermecanico.model.Mecanico> mecanicos = mecanicoDao.listarMecanicos();

    jComboBox2.removeAllItems();
    for (com.taller.tallermecanico.model.Mecanico m : mecanicos) {
        ((javax.swing.JComboBox) jComboBox2).addItem(new MecanicoComboItem(m.getId(), m.getNombre()));
    }
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}


